DROP TABLE Enrollments CASCADE CONSTRAINTS;
DROP TABLE Members CASCADE CONSTRAINTS;
DROP TABLE Courses CASCADE CONSTRAINTS;
DROP TABLE Projects CASCADE CONSTRAINTS;
DROP TABLE Students CASCADE CONSTRAINTS;
DROP VIEW StudentPairs;