(SELECT DISTINCT E.CID FROM Enrollments E
MINUS
SELECT DISTINCT E.CID FROM Enrollments E INNER JOIN Students S ON E.SID = S.SID
WHERE S.Major <> 'CS' OR S.Major IS NULL
GROUP BY E.CID HAVING COUNT(*) >= 5)
ORDER BY CID DESC;