CREATE VIEW StudentPairs AS 
SELECT DISTINCT E1.SID AS SID1, E2.SID AS SID2 FROM Enrollments E1, Enrollments E2
WHERE E1.CID = E2.CID AND E1.SID < E2.SID
MINUS
SELECT DISTINCT M1.SID, M2.SID FROM Members M1, Members M2
WHERE M1.PID = M2.PID AND M1.SID < M2.SID;