SELECT DISTINCT S0.SID, S0.Name FROM Students S0 JOIN Members M1 ON S0.SID = M1.SID JOIN Members M2 ON (M1.PID = M2.PID AND M1.SID <> M2.SID)
WHERE M2.SID IN
(SELECT DISTINCT S.SID FROM Students S, Enrollments E1, Courses C1, Enrollments E2, Courses C2, Enrollments E3, Courses C3
WHERE S.SID = E1.SID AND E1.CID = C1.CID AND S.SID = E2.SID AND E2.CID = C2.CID AND S.SID = E3.SID AND E3.CID = C3.CID
AND (C1.C_Name = 'EECS482' OR C1.C_Name = 'EECS483') AND (C2.C_Name = 'EECS484' OR C2.C_Name = 'EECS485') AND C3.C_Name = 'EECS280')
ORDER BY S0.Name DESC;