SELECT DISTINCT S.SID FROM Students S, Enrollments E1, Courses C1, Enrollments E2, Courses C2, Enrollments E3, Courses C3
WHERE S.SID = E1.SID AND E1.CID = C1.CID AND S.SID = E2.SID AND E2.CID = C2.CID AND S.SID = E3.SID AND E3.CID = C3.CID
AND ((C1.C_Name = 'EECS442' AND C2.C_Name = 'EECS445' AND C3.C_Name = 'EECS492')
OR (C1.C_Name = 'EECS482' AND C2.C_Name = 'EECS486')
OR C1.C_Name = 'EECS281')
ORDER BY S.SID ASC;
