SELECT DISTINCT S.SID FROM Students S, Enrollments E1, Courses C1, Enrollments E2, Courses C2, Enrollments E3, Courses C3
WHERE S.SID = E1.SID AND E1.CID = C1.CID AND S.SID = E2.SID AND E2.CID = C2.CID AND S.SID = E3.SID AND E3.CID = C3.CID
AND ((C1.C_Name = 'EECS442' AND C2.C_Name = 'EECS445' AND C3.C_Name = 'EECS492')
OR (C1.C_Name = 'EECS482' AND C2.C_Name = 'EECS486')
OR C1.C_Name = 'EECS281')
ORDER BY S.SID ASC;
--SELECT DISTINCT S.SID FROM Students S, Enrollments E 
--WHERE S.SID = E.SID 
--AND E.CID IN 
--SELECT C.CID FROM Courses C1, Courses C2, Courses C3 WHERE C1.CID = E.CID AND C2.CID = E.CID AND C3.CID = E.CID
--AND (C1.C_Name = 'EECS482' OR C1.C_Name = 'EECS483') AND (C1.C_Name = 'EECS484' OR C1.C_Name = 'EECS485') AND C3.C_Name = 'EECS280'
--ORDER BY S.SID ASC;